# Generated by Django 2.2.19 on 2023-01-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230130_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Описание поста'),
        ),
    ]
