# Generated by Django 2.2.19 on 2023-02-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230201_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
